name: Trigger auto deployment for workshopcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cicd.yml'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: workshopforredisflaskappln.azurecr.io
          username: ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: workshopforredisflaskappln.azurecr.io/web:${{ github.sha }}
          file: ./Dockerfile.web
          context: ./

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: workshopforredisflaskappln.azurecr.io/worker:${{ github.sha }}
          file: ./Dockerfile.worker
          context: ./

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: workshopforredisflaskappln.azurecr.io/redis:${{ github.sha }}
          file: ./Dockerfile.redis
          context: ./

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: workshopforredisflaskappln.azurecr.io/worker:${{ github.sha }}
          file: ./Dockerfile.dashboard
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WORKSHOPCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n workshopcontainerapp -g Workshop --server workshopforredisflaskappln.azurecr.io --username  ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n workshopcontainerapp -g Workshop --image workshopforredisflaskappln.azurecr.io/web:${{ github.sha }} --container-name master

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n workshopcontainerapp -g Workshop --server workshopforredisflaskappln.azurecr.io --username  ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n workshopcontainerapp -g Workshop --image workshopforredisflaskappln.azurecr.io/worker:${{ github.sha }} --container-name worker

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n workshopcontainerapp -g Workshop --server workshopforredisflaskappln.azurecr.io --username  ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n workshopcontainerapp -g Workshop --image workshopforredisflaskappln.azurecr.io/redis:${{ github.sha }} --container-name redis

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n workshopcontainerapp -g Workshop --server workshopforredisflaskappln.azurecr.io --username  ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.WORKSHOPCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n workshopcontainerapp -g Workshop --image workshopforredisflaskappln.azurecr.io/dashboard:${{ github.sha }} --container-name dashboard